### ISSUE TITLE
Information for README.md

### ISSUE THREAD

**Issue by ZeroDayOwl** [BradleyCodeU/bradleycodeu.github.io#48]
I needed a couple of information for the basic documentation. For example:

- Whether any person can contribute to the list of example projects or is it just for the students taking part in the classes to contribute
- The list of maintainer/s people can contact if they run into an issue (GitHub usernames preferably)
- And possibly any other information you want included in the doc

I have sort of a draft ready if you want me to push to the repo.

**Comment by ohiofi** [comment]
- Example projects are selected and posted by the instructor @ohiofi 
- I am the maintainer to contact @ohiofi 
- Basically… this site holds the curriculum material for Bradley High School coding classes.

Thanks again!

**Comment by ZeroDayOwl** [comment]
Thank you for the information! I will be pushing my commit within a while.

And you're welcome!

**Comment by ZeroDayOwl** [comment]
And it is pushed #49
